import os

if os.environ.get("COVERAGE_MODE", "0") == "1":
    os.environ["TESTING_INTERP"] = "1"

import numpy as np

import pytest
from numpy.testing import assert_allclose

from cosmo_numba.math.interpolate.interpolate_1D import (
    AkimaInterp1D,
    nb_interp1d,
    nb_interp1d_func,
)


def create_interp1d_data(
    f, a, b, h, k, p=False, c=True, e=0, log_interp=False
):
    """
    Helper function to create data array for nb_interp1d_func.

    Parameters
    ----------
    f : array_like
        Data to be interpolated
    a : float
        The lower bound of the interpolation region
    b : float
        The upper bound of the interpolation region
    h : float
        The grid-spacing at which f is given
    k : int
        Order of local Taylor expansions (1, 3, 5, 7, or 9)
    p : bool, optional
        Whether the dimension is taken to be periodic (default is False)
    c : bool, optional
        Whether the array should be padded to allow accurate close eval
        (default is True)
    e : int, optional
        Extrapolation distance, how far to allow extrap, in units of h
        (needs to be an integer, default is 0)
    log_interp : bool, optional
        Whether x is in log space (default is False)

    Returns
    -------
    data : ndarray
        Data array formatted for nb_interp1d_func
    """
    len_f = len(f)
    data = np.zeros(1 + len_f + 8, dtype=np.float64)
    data[0] = len_f
    data[1 : 1 + len_f] = f
    data[1 + len_f + 0] = a
    data[1 + len_f + 1] = b
    data[1 + len_f + 2] = h
    data[1 + len_f + 3] = float(k)
    data[1 + len_f + 4] = float(p)
    data[1 + len_f + 5] = float(c)
    data[1 + len_f + 6] = float(e)
    data[1 + len_f + 7] = float(log_interp)
    return data


class InterpolatorWrapper:
    """
    Wrapper class to provide uniform interface for both nb_interp1d class
    and nb_interp1d_func functional form.

    NOTE:
    This class have been largely generated by AI and modified to fit
    expectations.
    """

    def __init__(
        self,
        interp_type,
        a,
        b,
        h,
        f,
        k,
        p=False,
        c=True,
        e=0,
        log_interp=False,
    ):
        self.interp_type = interp_type
        if interp_type == "class":
            self.interp = nb_interp1d(
                a, b, h, f, k=k, p=p, c=c, e=e, log_interp=log_interp
            )
        elif interp_type == "func":
            self.data = create_interp1d_data(
                f, a, b, h, k, p, c, e, log_interp=log_interp
            )

    def eval(self, xout):
        """
        Evaluate interpolation at points xout.

        Parameters
        ----------
        xout : array_like
            Points where to interpolate

        Returns
        -------
        yout : ndarray
            Interpolated values
        """
        if self.interp_type == "class":
            return self.interp.eval(xout)
        elif self.interp_type == "func":
            # For functional form, we need to call it for each point
            yout = np.zeros_like(xout)

            for i, x in enumerate(xout):
                yout[i] = nb_interp1d_func(float(x), self.data)
            return yout


class TestAkimaInterp1D:
    """
    Test suite for AkimaInterp1D class
    """

    def test_eval(self):
        """
        Test the evaluation of the Akima interpolation against known values.
        Test from Scipy testing of Akima1DInterpolator.
        """
        x = np.arange(0.0, 11.0, dtype=np.float64)
        y = np.array([0.0, 2.0, 1.0, 3.0, 2.0, 6.0, 5.5, 5.5, 2.7, 5.1, 3.0])
        ak = AkimaInterp1D(x, y)
        xi = np.array(
            [0.0, 0.5, 1.0, 1.5, 2.5, 3.5, 4.5, 5.1, 6.5, 7.2, 8.6, 9.9, 10.0]
        )
        yi = np.array(
            [
                0.0,
                1.375,
                2.0,
                1.5,
                1.953125,
                2.484375,
                4.1363636363636366866103344,
                5.9803623910336236590978842,
                5.5067291516462386624652936,
                5.2031367459745245795943447,
                4.1796554159017080820603951,
                3.4110386597938129327189927,
                3.0,
            ]
        )

        assert_allclose(ak.eval(xi), yi)

    def test_eval_at_data_points(self):
        """
        Test that interpolation returns exact values at data points.
        """
        x = np.array([0.0, 1.0, 2.0, 3.0, 4.0])
        y = np.array([1.0, 2.0, 1.5, 3.0, 2.0])
        ak = AkimaInterp1D(x, y)
        assert_allclose(ak.eval(x), y)

    def test_extrapolation(self):
        """
        Test the extrapolation behavior of the Akima interpolation.
        """
        x = np.linspace(0.0, 1.0, 10, dtype=np.float64)
        y = np.linspace(0.0, 1.0, 10, dtype=np.float64)
        ak = AkimaInterp1D(x, y)

        xi_r = np.array([2.0])
        xi_l = np.array([-1.0])

        assert_allclose(ak.eval(xi_r), np.array([0.0]))
        assert_allclose(ak.eval(xi_l), np.array([0.0]))

        # Now update extrapolation values
        ak.update_extrapolation(1.0, 1.0)

        assert_allclose(ak.eval(xi_r), np.array([1.0]))
        assert_allclose(ak.eval(xi_l), np.array([1.0]))

    def test_raised_errors(self):
        """
        Test that AkimaInterp1D raises errors for invalid inputs.
        """
        x_1 = np.array([0.0, 1.0], dtype=np.float64)
        x_2 = np.array([0.0, 1.0, 2.0], dtype=np.float64)
        y = np.array([0.0, 1.0], dtype=np.float64)

        with pytest.raises(ValueError):
            AkimaInterp1D(x_1, y)
        with pytest.raises(ValueError):
            AkimaInterp1D(x_2, y)

        x = np.linspace(1.0, 0.0, 10, dtype=np.float64)
        y = np.linspace(0.0, 1.0, 10, dtype=np.float64)
        with pytest.raises(ValueError):
            AkimaInterp1D(x, y)


class TestNbInterp1D:
    """
    Robust test suite for nb_interp1d and nb_interp1d_func.

    Verified mathematical properties:

    • Polynomial exactness up to degree k < 5
    • Convergence order k+1 for smooth functions
    • Periodic wrapping correctness
    • Class / functional backend equivalence

    NOTE:
    High-order tests (k > 5) are skipped due to numerical instability as stated
    in the documentation of the original fast_interp code.

    NOTE:
    Those tests have been largely generated by AI and modified to fit
    expectations.
    """

    # ================================================================
    # Polynomial exactness
    # ================================================================

    @pytest.mark.parametrize("interp_type", ["class", "func"])
    @pytest.mark.parametrize("k", [1, 3, 5, 7, 9])
    def test_polynomial_exactness(self, interp_type, k):
        """
        (k+1)-point Lagrange interpolation exactly reproduces polynomials of
        degree ≤ k.

        Tested away from boundaries to avoid padding artifacts.
        """

        if k > 5:
            pytest.skip(
                "Skipping high-order convergence (not reliable for k>5)"
            )

        a, b = -2.0, 3.0
        n = 140

        x = np.linspace(a, b, n, dtype=np.float64)
        h = x[1] - x[0]

        x_eval = np.linspace(a + 3 * h, b - 3 * h, 500)

        for degree in range(k + 1):
            y = x**degree

            interp = InterpolatorWrapper(
                interp_type,
                a,
                b,
                h,
                y,
                k=k,
                c=0,
            )

            y_eval = interp.eval(x_eval)

            assert_allclose(
                y_eval,
                x_eval**degree,
                rtol=0.0,
                atol=1e-8,
                err_msg=f"type={interp_type}, k={k}, degree={degree}",
            )

    # ================================================================
    # Order of accuracy
    # ================================================================

    @pytest.mark.parametrize("interp_type", ["class", "func"])
    @pytest.mark.parametrize("k", [1, 3, 5, 7, 9])
    def test_order_of_accuracy(self, interp_type, k):
        """
        Interpolation error must scale as:

            ||f - I_h f|| = O(h^{k+1})

        Verified only in the asymptotic regime.
        """

        if k > 5:
            pytest.skip(
                "Skipping high-order convergence (not reliable for k>5)"
            )

        def f(x):
            return np.sin(x)

        xi = np.linspace(0.0, 2 * np.pi, 8000)
        f_ref = f(xi)

        hs = []
        errors = []

        for n in [40, 80, 160, 320]:
            x = np.linspace(0.0, 2 * np.pi, n, dtype=np.float64)
            h = x[1] - x[0]
            y = f(x)

            interp = InterpolatorWrapper(
                interp_type,
                x[0],
                x[-1],
                h,
                y,
                k=k,
            )

            yi = interp.eval(xi)

            err = np.max(np.abs(yi - f_ref))

            hs.append(h)
            errors.append(err)

        hs = np.asarray(hs)
        errors = np.asarray(errors)

        slopes = np.log(errors[:-1] / errors[1:]) / np.log(hs[:-1] / hs[1:])

        expected = k + 1

        # Accept asymptotic convergence
        assert np.any(np.abs(slopes - expected) < 0.8), f"""
        Failed order test:

        interp_type = {interp_type}
        k           = {k}
        slopes      = {slopes}
        expected    = {expected}
        """

    # ================================================================
    # Periodic interpolation
    # ================================================================

    @pytest.mark.parametrize("interp_type", ["class", "func"])
    @pytest.mark.parametrize("k", [3, 5, 7, 9])
    def test_periodic(self, interp_type, k):
        """
        Verifies periodic wrapping logic.
        """

        if k > 5:
            pytest.skip(
                "Skipping high-order convergence (not reliable for k>5)"
            )

        L = 2 * np.pi
        n = 128

        x = np.linspace(0.0, L, n, endpoint=False)
        h = x[1] - x[0]

        y = np.sin(x)

        interp = InterpolatorWrapper(
            interp_type,
            0.0,
            L,
            h,
            y,
            k=k,
            p=True,
        )

        x_eval = np.linspace(-L, 2 * L, 2000)
        y_eval = interp.eval(x_eval)

        assert_allclose(
            y_eval,
            np.sin(x_eval),
            rtol=1e-6,
            atol=1e-8,
        )

    # ================================================================
    # Backend equivalence
    # ================================================================

    @pytest.mark.parametrize("k", [1, 3, 5, 7, 9])
    def test_class_and_func_match(self, k):
        """
        Functional and class APIs must be numerically identical.
        """

        if k > 5:
            pytest.skip(
                "Skipping high-order convergence (not reliable for k>5)"
            )

        x = np.linspace(0.0, 6.0, 160)
        h = x[1] - x[0]
        y = np.exp(-x)

        xi = np.linspace(0.0, 6.0, 800)

        interp_class = InterpolatorWrapper(
            "class",
            x[0],
            x[-1],
            h,
            y,
            k=k,
            e=1,
        )

        interp_func = InterpolatorWrapper(
            "func",
            x[0],
            x[-1],
            h,
            y,
            k=k,
            e=1,
        )

        assert_allclose(
            interp_class.eval(xi),
            interp_func.eval(xi),
            rtol=0.0,
            atol=0.0,
        )

    # -------------------------------------------------------------------------
    # 4. Log-space stability (cosmology use case)
    # -------------------------------------------------------------------------

    @pytest.mark.parametrize("k", [3, 5, 7, 9])
    def test_log_space_interpolation(self, k):
        """
        Validate behavior on wide-dynamic-range spectra.
        """

        if k > 5:
            pytest.skip(
                "Skipping high-order convergence (not reliable for k>5)"
            )

        n = 120
        x_min, x_max = 1e-3, 1e3

        x = np.logspace(np.log10(x_min), np.log10(x_max), n)
        y = x ** (-1.5) * np.exp(-x / 100.0)

        logx = np.log(x)
        h = logx[1] - logx[0]

        interp = InterpolatorWrapper(
            "class",
            logx[0],
            logx[-1],
            h,
            y,
            k=k,
            log_interp=True,
        )

        x_test = np.logspace(
            np.log10(x_min * 2),
            np.log10(x_max / 2),
            80,
        )

        y_test = interp.eval(x_test)
        y_ref = x_test ** (-1.5) * np.exp(-x_test / 100.0)

        assert_allclose(
            y_test,
            y_ref,
            rtol=5e-4,
            atol=5e-6,
        )

    def test_class_error(self):
        """
        Test that nb_interp1d class raises error for invalid inputs.
        """
        x = np.linspace(0.0, 6.0, 160)
        h = x[1] - x[0]
        y = np.exp(-x)

        xi = np.linspace(0.0, 6.0, 800)

        interp_class = InterpolatorWrapper(
            "class",
            x[0],
            x[-1],
            h,
            y,
            k=11,
            e=1,
        )

        with pytest.raises(ValueError):
            interp_class.eval(xi)

    @pytest.mark.parametrize(
        "k",
        [
            1,
            3,
            5,
            7,
            9,
        ],
    )
    def test_polynomial_exactness_coarse_grid(self, k):
        """
        The order-k interpolant reproduces a polynomial of degree k between
        the samples, also on a grid coarse enough that a wrong top-degree
        coefficient is not hidden by a small h^k.
        """
        x = np.linspace(-1.0, 1.0, 17)
        poly = np.polynomial.Polynomial(np.ones(k + 1))
        interp = nb_interp1d(x[0], x[-1], x[1] - x[0], poly(x), k=k)

        x_eval = np.linspace(-0.45, 0.45, 40)
        assert_allclose(interp.eval(x_eval), poly(x_eval), rtol=0, atol=1e-10)

    @pytest.mark.xfail(
        strict=True,
        reason="the cell index is not clamped, so between the last padded "
        "cell and the upper clamping bound the stencil reads past the padded "
        "samples whenever b exceeds a + (n - 1) h, by design or by round-off",
    )
    @pytest.mark.parametrize("k", [1, 3, 5, 7, 9])
    def test_upper_clamp_stays_in_data(self, k):
        """
        Up to the upper clamping bound b + e h, the interpolant is built from
        the padded samples also when b lies past the last sample, as for a
        sub-grid of an irregular grid with its mean step: a line is
        reproduced there, and held at the bound beyond it.
        """
        n, h, e = 30, 0.1, 1
        x = np.arange(n) * h
        b = x[-1] + 0.5 * h
        interp = nb_interp1d(x[0], b, h, 0.3 + 1.7 * x, k, False, True, e)

        x_eval = x[-1] + h * np.array([0.5, 1.1, 1.3, 1.45, 3.0])
        expected = 0.3 + 1.7 * np.minimum(x_eval, b + e * h)
        assert_allclose(interp.eval(x_eval), expected, rtol=0, atol=1e-11)
